### ISSUE TITLE
Extra information on routes

### ISSUE THREAD

**Issue by benjamintd** [benjamintd/mapbox-maps#25]
Here is additional information that might be useful:
- [x] Add an elevation profile for bike directions (see [this example](https://bl.ocks.org/colleenmcginnis/fd1ae6cb18917c79c3e45c462e8f659e))
- [ ] Add turn by turn instructions and traffic-on-route for car directions

**Comment by SrihariThalla** [comment]
Turn-by-turn is indeed something that everyone needs.

The elevation profile example can be improved with more details, like how slant a road is between the points - too slant / going downhill, uphill, etc.,.
