### ISSUE TITLE
The marker should not disappear when clicking on the map

### ISSUE THREAD

**Issue by sarahmamy** [benjamintd/mapbox-maps#38]
*User Story*
Looking for an address, typing it on the search bar, entry.
I see the marker, right click on the marker to copy paste GPS coordinates. 
Then, a click on the map makes the marker disappear. 'Where is my marker?' 
While, as a user, I was just expecting the coordinates window to be closed.

But I would also expect a click on the map to keep the marker (as Google Maps does)

![image](https://user-images.githubusercontent.com/16375291/27429473-7c2d3d0c-5745-11e7-979a-466abc606d2a.png)
 
Sorry for the English grammar mistakes

**Comment by benjamintd** [comment]
I agree that removing the marker on click is a bad user experience, in retrospect.

I had problems on mobile trying to pan the map: the browser thinks I clicked, and my searched location disappears.

The only way to quit the search should be through the exit button.

cc @sarahmamy

**Comment by benjamintd** [comment]
Solved in #39
