### ISSUE TITLE
SSL Warning

### ISSUE THREAD

**Issue by lukasmartinelli** [benjamintd/mapbox-maps#51]
https://benjamintd.github.io/mapbox-maps/ redirects to https://www.benjamintd.com/mapbox-maps/ and then SSL is broken.

**Comment by benjamintd** [comment]
I should fix that indeed, I've had broken DNS on my domain for a moment but did not get a chance to fix it yet.

In the meantime, https://maps.benjamintd.com should work, except that URL encoded coordinates and places will throw a 404.

**Comment by benjamintd** [comment]
https://maps.benjamintd.com is now the URL to use

> except that URL encoded coordinates and places will throw a 404.

This was fixed in #53
